<?php
require_once __DIR__ . '/../includes/init.php';
Auth::requireRole(['super_admin', 'admin']);

require_once base_path('app/Repositories/MerchantRepository.php');
require_once base_path('app/Repositories/UserRepository.php');
require_once base_path('app/Repositories/WalletRepository.php');
require_once base_path('app/Services/TransactionService.php');
require_once base_path('app/Services/WithdrawalService.php');
require_once base_path('app/Services/AuditLogService.php');

$merchantRepo = new MerchantRepository();
$userRepo = new UserRepository();
$walletRepo = new WalletRepository();
$txService = new TransactionService();
$wdService = new WithdrawalService();
$auditService = new AuditLogService();

$merchantId = $_GET['id'] ?? '';
$merchant = $merchantRepo->find($merchantId);
if (!$merchant) { flash('error', 'Merchant tidak ditemukan.'); redirect('/admin/merchants.php'); }

// Handle POST actions
if (is_post()) {
    Auth::verifyCsrf();
    $action = $_POST['_action'] ?? '';

    if ($action === 'update_info') {
        $merchantRepo->update($merchantId, [
            'business_name' => sanitize($_POST['business_name'] ?? ''),
            'owner_name' => sanitize($_POST['owner_name'] ?? ''),
            'email' => sanitize($_POST['email'] ?? ''),
            'phone' => sanitize($_POST['phone'] ?? ''),
            'address' => sanitize($_POST['address'] ?? ''),
            'city' => sanitize($_POST['city'] ?? ''),
            'website' => sanitize($_POST['website'] ?? ''),
            'business_type' => sanitize($_POST['business_type'] ?? ''),
            'updated_at' => now(),
        ]);
        $auditService->log(Auth::id(), Auth::role(), $merchantId, 'merchant_updated', "Merchant info updated", []);
        flash('success', 'Info merchant berhasil diperbarui.');


    } elseif ($action === 'update_status') {
        $newStatus = sanitize($_POST['new_status'] ?? '');
        if (in_array($newStatus, ['pending','active','suspended','rejected'])) {
            $merchantRepo->update($merchantId, ['status' => $newStatus, 'updated_at' => now()]);
            $auditService->log(Auth::id(), Auth::role(), $merchantId, 'merchant_status_changed', "Status changed to {$newStatus}", ['old' => $merchant['status'], 'new' => $newStatus]);
            flash('success', 'Status merchant diperbarui.');
        }

    } elseif ($action === 'update_fee') {
        $merchantRepo->update($merchantId, [
            'fee_type' => sanitize($_POST['fee_type'] ?? 'percentage'),
            'fee_value' => (float)($_POST['fee_value'] ?? 0),
            'fee_flat' => (float)($_POST['fee_flat'] ?? 0),
            'updated_at' => now(),
        ]);
        $auditService->log(Auth::id(), Auth::role(), $merchantId, 'merchant_fee_updated', "Fee updated", $_POST);
        flash('success', 'Fee merchant diperbarui.');

    } elseif ($action === 'update_urls') {
        $merchantRepo->update($merchantId, [
            'webhook_url' => sanitize($_POST['webhook_url'] ?? ''),
            'redirect_url' => sanitize($_POST['redirect_url'] ?? ''),
            'updated_at' => now(),
        ]);
        flash('success', 'URL merchant diperbarui.');

    } elseif ($action === 'regenerate_key') {
        $newKey = $merchantRepo->regenerateApiKey($merchantId);
        $auditService->log(Auth::id(), Auth::role(), $merchantId, 'api_key_regenerated', "API key regenerated by admin", []);
        flash('success', 'API key berhasil di-regenerate.');

    } elseif ($action === 'add_staff') {
        $staffEmail = sanitize($_POST['staff_email'] ?? '');
        $staffName = sanitize($_POST['staff_name'] ?? '');
        $staffPassword = $_POST['staff_password'] ?? '';
        $staffPermissions = $_POST['permissions'] ?? [];

        if (empty($staffName) || !is_valid_email($staffEmail) || strlen($staffPassword) < 8) {
            flash('error', 'Data staff tidak valid. Nama, email valid, dan password min 8 karakter.');
        } elseif ($userRepo->findByEmail($staffEmail)) {
            flash('error', 'Email sudah terdaftar.');
        } else {
            $userRepo->create([
                'id' => generate_uuid(),
                'merchant_id' => $merchantId,
                'name' => $staffName,
                'email' => $staffEmail,
                'password_hash' => password_hash($staffPassword, PASSWORD_DEFAULT),
                'role' => 'staff_merchant',
                'status' => 'active',
                'permissions' => $staffPermissions,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
            $auditService->log(Auth::id(), Auth::role(), $merchantId, 'staff_added', "Staff {$staffName} added", ['email' => $staffEmail]);
            flash('success', "Staff {$staffName} berhasil ditambahkan.");
        }

    } elseif ($action === 'remove_staff') {
        $staffId = $_POST['staff_id'] ?? '';
        $staff = $userRepo->find($staffId);
        if ($staff && $staff['merchant_id'] === $merchantId && $staff['role'] === 'staff_merchant') {
            $userRepo->delete($staffId);
            $auditService->log(Auth::id(), Auth::role(), $merchantId, 'staff_removed', "Staff {$staff['name']} removed", []);
            flash('success', "Staff berhasil dihapus.");
        }
    }
    redirect("/admin/merchant-detail.php?id={$merchantId}&tab=" . ($_POST['_tab'] ?? 'info'));
}

// Reload merchant data after potential updates
$merchant = $merchantRepo->find($merchantId);
$wallet = $walletRepo->findByMerchant($merchantId);
$staffUsers = $userRepo->findByMerchant($merchantId);
$stats = $txService->getMerchantStats($merchantId);
$activeTab = $_GET['tab'] ?? 'info';

$pageTitle = 'Detail Merchant: ' . e($merchant['business_name']);
require_once __DIR__ . '/../includes/header.php';
require_once __DIR__ . '/../includes/admin_layout.php';
?>


<a href="/admin/merchants.php" class="inline-flex items-center gap-1 text-sm text-slate-500 active:text-slate-700 mb-4">
    <svg class="w-4 h-4" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M15 19l-7-7 7-7"/></svg> Kembali
</a>

<!-- Quick Approve Banner (only for pending merchants) -->
<?php if ($merchant['status'] === 'pending'): ?>
<div class="mb-5 p-4 bg-amber-50 border border-amber-200 rounded-xl">
    <div class="flex items-center justify-between gap-3">
        <div>
            <p class="text-sm font-semibold text-amber-900">Merchant menunggu approval</p>
            <p class="text-xs text-amber-700 mt-0.5"><?= e($merchant['business_name']) ?> &mdash; <?= e($merchant['email']) ?></p>
        </div>
        <form method="POST" class="flex-shrink-0">
            <?= csrf_field() ?>
            <input type="hidden" name="_action" value="update_status">
            <input type="hidden" name="_tab" value="info">
            <input type="hidden" name="new_status" value="active">
            <button type="submit" onclick="return confirm('Approve merchant ini?')" class="px-4 py-2 bg-emerald-600 text-white text-xs font-semibold rounded-lg active:bg-emerald-700">
                Approve
            </button>
        </form>
    </div>
</div>
<?php endif; ?>

<!-- Summary Cards -->
<div class="grid grid-cols-2 gap-3 mb-5">
    <div class="bg-white rounded-xl border border-slate-200 p-3">
        <p class="text-[11px] text-slate-500 uppercase tracking-wide">Status</p>
        <span class="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-semibold mt-1.5 <?= status_badge_class($merchant['status']) ?>"><?= ucfirst($merchant['status']) ?></span>
    </div>
    <div class="bg-white rounded-xl border border-slate-200 p-3">
        <p class="text-[11px] text-slate-500 uppercase tracking-wide">Saldo</p>
        <p class="text-base font-bold text-emerald-600 mt-1"><?= format_currency($wallet['available_balance'] ?? 0) ?></p>
    </div>
    <div class="bg-white rounded-xl border border-slate-200 p-3">
        <p class="text-[11px] text-slate-500 uppercase tracking-wide">Transaksi</p>
        <p class="text-base font-bold text-slate-800 mt-1"><?= number_format($stats['total_transactions']) ?></p>
    </div>
    <div class="bg-white rounded-xl border border-slate-200 p-3">
        <p class="text-[11px] text-slate-500 uppercase tracking-wide">Revenue</p>
        <p class="text-base font-bold text-slate-800 mt-1"><?= format_currency($stats['total_revenue']) ?></p>
    </div>
</div>

<!-- Tab Navigation -->
<div class="border-b border-slate-200 mb-5 -mx-1">
    <nav class="flex -mb-px overflow-x-auto scrollbar-hide px-1">
        <?php $tabs = ['info'=>'Info','fee'=>'Fee & API','urls'=>'Webhook','staff'=>'Staff','wallet'=>'Wallet'];
        foreach ($tabs as $tk => $tl): ?>
        <a href="?id=<?= e($merchantId) ?>&tab=<?= $tk ?>" class="px-3 py-2.5 text-xs font-medium whitespace-nowrap border-b-2 transition-colors <?= $activeTab === $tk ? 'border-blue-600 text-blue-600' : 'border-transparent text-slate-500 active:text-slate-700' ?>">
            <?= $tl ?>
        </a>
        <?php endforeach; ?>
    </nav>
</div>

<div class="max-w-2xl">
<div class="bg-white rounded-xl border border-slate-200 p-5">

<?php if ($activeTab === 'info'): ?>
<h3 class="text-lg font-semibold text-slate-800 mb-4">Informasi Bisnis</h3>
<form method="POST" class="space-y-4">
    <?= csrf_field() ?>
    <input type="hidden" name="_action" value="update_info">
    <input type="hidden" name="_tab" value="info">
    <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div><label class="block text-sm font-medium text-slate-700 mb-1">Nama Bisnis</label>
            <input type="text" name="business_name" value="<?= e($merchant['business_name']) ?>" class="w-full px-4 py-2.5 border border-slate-300 rounded-lg text-sm"></div>
        <div><label class="block text-sm font-medium text-slate-700 mb-1">Nama Pemilik</label>
            <input type="text" name="owner_name" value="<?= e($merchant['owner_name']) ?>" class="w-full px-4 py-2.5 border border-slate-300 rounded-lg text-sm"></div>
        <div><label class="block text-sm font-medium text-slate-700 mb-1">Email</label>
            <input type="email" name="email" value="<?= e($merchant['email']) ?>" class="w-full px-4 py-2.5 border border-slate-300 rounded-lg text-sm"></div>
        <div><label class="block text-sm font-medium text-slate-700 mb-1">Telepon</label>
            <input type="text" name="phone" value="<?= e($merchant['phone'] ?? '') ?>" class="w-full px-4 py-2.5 border border-slate-300 rounded-lg text-sm"></div>
        <div><label class="block text-sm font-medium text-slate-700 mb-1">Tipe Bisnis</label>
            <select name="business_type" class="w-full px-3 py-2.5 border border-slate-300 rounded-lg text-sm">
                <?php foreach (['','retail','food_beverage','services','digital','education','other'] as $bt): ?>
                <option value="<?= $bt ?>" <?= ($merchant['business_type'] ?? '') === $bt ? 'selected' : '' ?>><?= $bt ? ucfirst(str_replace('_',' ',$bt)) : '-- Pilih --' ?></option>
                <?php endforeach; ?>
            </select></div>
        <div><label class="block text-sm font-medium text-slate-700 mb-1">Website</label>
            <input type="url" name="website" value="<?= e($merchant['website'] ?? '') ?>" class="w-full px-4 py-2.5 border border-slate-300 rounded-lg text-sm"></div>
    </div>
    <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div><label class="block text-sm font-medium text-slate-700 mb-1">Kota</label>
            <input type="text" name="city" value="<?= e($merchant['city'] ?? '') ?>" class="w-full px-4 py-2.5 border border-slate-300 rounded-lg text-sm"></div>
        <div><label class="block text-sm font-medium text-slate-700 mb-1">Alamat</label>
            <input type="text" name="address" value="<?= e($merchant['address'] ?? '') ?>" class="w-full px-4 py-2.5 border border-slate-300 rounded-lg text-sm"></div>
    </div>
    <p class="text-xs text-slate-400">ID: <?= e($merchantId) ?> | Terdaftar: <?= format_date($merchant['created_at']) ?></p>
    <button type="submit" class="w-full sm:w-auto px-6 py-2.5 bg-blue-600 text-white rounded-lg text-sm font-medium active:bg-blue-700">Simpan Info</button>
</form>

<!-- Status Update — separate form to avoid conflict -->
<form method="POST" class="mt-6 pt-5 border-t border-slate-200">
    <?= csrf_field() ?>
    <input type="hidden" name="_action" value="update_status">
    <input type="hidden" name="_tab" value="info">
    <label class="block text-sm font-semibold text-slate-800 mb-3">Ubah Status Merchant</label>
    <div class="grid grid-cols-2 sm:grid-cols-4 gap-2 mb-4">
        <?php
        $statusColors = [
            'pending' => 'border-amber-300 bg-amber-50 text-amber-800',
            'active' => 'border-emerald-300 bg-emerald-50 text-emerald-800',
            'suspended' => 'border-red-300 bg-red-50 text-red-800',
            'rejected' => 'border-slate-300 bg-slate-50 text-slate-800',
        ];
        foreach (['pending','active','suspended','rejected'] as $st): ?>
        <label class="flex items-center justify-center gap-2 cursor-pointer px-3 py-3 rounded-xl border-2 transition-all <?= $merchant['status'] === $st ? $statusColors[$st] . ' ring-2 ring-offset-1 ring-blue-400' : 'border-slate-200 hover:border-slate-300' ?>">
            <input type="radio" name="new_status" value="<?= $st ?>" <?= $merchant['status'] === $st ? 'checked' : '' ?> class="sr-only peer">
            <span class="text-xs font-semibold peer-checked:underline"><?= ucfirst($st) ?></span>
        </label>
        <?php endforeach; ?>
    </div>
    <?php if ($merchant['status'] === 'pending'): ?>
    <div class="p-3 bg-emerald-50 border border-emerald-200 rounded-lg mb-4">
        <p class="text-xs text-emerald-800">Pilih <strong>Active</strong> lalu klik tombol di bawah untuk approve merchant ini.</p>
    </div>
    <?php endif; ?>
    <button type="submit" onclick="return confirm('Ubah status merchant ke ' + document.querySelector('input[name=new_status]:checked').value + '?')" class="w-full sm:w-auto px-6 py-2.5 bg-slate-900 text-white rounded-lg text-sm font-medium active:bg-slate-800">
        Update Status
    </button>
</form>


<?php elseif ($activeTab === 'fee'): ?>
<h3 class="text-lg font-semibold text-slate-800 mb-4">Fee & API Key</h3>
<!-- Fee Settings -->
<form method="POST" class="space-y-4 mb-6">
    <?= csrf_field() ?>
    <input type="hidden" name="_action" value="update_fee">
    <input type="hidden" name="_tab" value="fee">
    <p class="text-sm text-slate-500">Override fee global untuk merchant ini.</p>
    <div class="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <div><label class="block text-sm font-medium text-slate-700 mb-1">Tipe Fee</label>
            <select name="fee_type" id="feeType" onchange="updateFeePreview()" class="w-full px-3 py-2.5 border border-slate-300 rounded-lg text-sm">
                <option value="percentage" <?= ($merchant['fee_type'] ?? '') === 'percentage' ? 'selected' : '' ?>>Percentage (%)</option>
                <option value="flat" <?= ($merchant['fee_type'] ?? '') === 'flat' ? 'selected' : '' ?>>Flat (Rp)</option>
                <option value="hybrid" <?= ($merchant['fee_type'] ?? '') === 'hybrid' ? 'selected' : '' ?>>Hybrid (% + Rp)</option>
            </select></div>
        <div><label class="block text-sm font-medium text-slate-700 mb-1">Fee Value</label>
            <input type="number" name="fee_value" id="feeValue" step="0.01" value="<?= e($merchant['fee_value'] ?? 0) ?>" onchange="updateFeePreview()" class="w-full px-4 py-2.5 border border-slate-300 rounded-lg text-sm"></div>
        <div><label class="block text-sm font-medium text-slate-700 mb-1">Flat (hybrid)</label>
            <input type="number" name="fee_flat" id="feeFlat" value="<?= e($merchant['fee_flat'] ?? 0) ?>" onchange="updateFeePreview()" class="w-full px-4 py-2.5 border border-slate-300 rounded-lg text-sm"></div>
    </div>
    <!-- Live Preview -->
    <div class="p-4 bg-emerald-50 border border-emerald-200 rounded-lg">
        <p class="text-sm font-medium text-emerald-800 mb-1">Preview Fee (simulasi Rp 100.000)</p>
        <p class="text-lg font-bold text-emerald-700" id="feePreview">-</p>
        <p class="text-xs text-emerald-600" id="feeNetPreview"></p>
    </div>
    <button type="submit" class="px-6 py-2.5 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700">Simpan Fee</button>
</form>
<!-- API Key -->
<div class="border-t border-slate-200 pt-4">
    <h4 class="text-sm font-semibold text-slate-800 mb-3">API Key</h4>
    <div class="flex items-center gap-2 mb-3">
        <input type="text" value="<?= e($merchant['api_key'] ?? '') ?>" readonly id="merchantApiKey" class="flex-1 px-4 py-2.5 bg-slate-900 text-emerald-400 font-mono text-sm rounded-lg border-0">
        <button onclick="navigator.clipboard.writeText(document.getElementById('merchantApiKey').value);showToast('Copied!')" class="px-4 py-2.5 bg-blue-600 text-white rounded-lg text-sm">Copy</button>
    </div>
    <form method="POST" onsubmit="return confirm('API key lama akan invalid. Lanjutkan?')">
        <?= csrf_field() ?><input type="hidden" name="_action" value="regenerate_key"><input type="hidden" name="_tab" value="fee">
        <button class="px-4 py-2 bg-red-50 text-red-600 rounded-lg text-xs font-medium hover:bg-red-100">Regenerate API Key</button>
    </form>
</div>
<script>
function updateFeePreview() {
    const type = document.getElementById('feeType').value;
    const val = parseFloat(document.getElementById('feeValue').value) || 0;
    const flat = parseFloat(document.getElementById('feeFlat').value) || 0;
    const amount = 100000;
    let fee = 0;
    if (type === 'percentage') fee = Math.round(amount * val / 100);
    else if (type === 'flat') fee = val;
    else fee = Math.round(amount * val / 100) + flat;
    document.getElementById('feePreview').textContent = 'Fee: Rp ' + fee.toLocaleString('id-ID');
    document.getElementById('feeNetPreview').textContent = 'Net merchant: Rp ' + (amount - fee).toLocaleString('id-ID') + ' dari Rp 100.000';
}
updateFeePreview();
</script>


<?php elseif ($activeTab === 'urls'): ?>
<h3 class="text-lg font-semibold text-slate-800 mb-4">Webhook & Redirect URL</h3>
<form method="POST" class="space-y-4">
    <?= csrf_field() ?>
    <input type="hidden" name="_action" value="update_urls">
    <input type="hidden" name="_tab" value="urls">
    <div>
        <label class="block text-sm font-medium text-slate-700 mb-1">Webhook URL</label>
        <input type="url" name="webhook_url" value="<?= e($merchant['webhook_url'] ?? '') ?>" class="w-full px-4 py-2.5 border border-slate-300 rounded-lg text-sm" placeholder="https://...">
        <p class="text-xs text-slate-400 mt-1">POST request dikirim ke URL ini saat status transaksi berubah.</p>
    </div>
    <div>
        <label class="block text-sm font-medium text-slate-700 mb-1">Redirect URL (setelah bayar)</label>
        <input type="url" name="redirect_url" value="<?= e($merchant['redirect_url'] ?? '') ?>" class="w-full px-4 py-2.5 border border-slate-300 rounded-lg text-sm" placeholder="https://...">
    </div>
    <button type="submit" class="px-6 py-2.5 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700">Simpan URL</button>
</form>

<?php elseif ($activeTab === 'staff'): ?>
<h3 class="text-lg font-semibold text-slate-800 mb-4">Staff Merchant</h3>
<p class="text-sm text-slate-500 mb-4">Kelola staff yang memiliki akses ke dashboard merchant ini.</p>

<?php
$staffList = array_filter($staffUsers, fn($u) => $u['role'] === 'staff_merchant');
$ownerUser = array_filter($staffUsers, fn($u) => $u['role'] === 'merchant');
$ownerUser = array_values($ownerUser);
?>

<!-- Owner Info -->
<?php if (!empty($ownerUser)): ?>
<div class="p-3 bg-blue-50 border border-blue-200 rounded-lg mb-4 flex items-center gap-3">
    <div class="w-8 h-8 bg-blue-600 rounded-full flex items-center justify-center text-white text-sm font-bold"><?= strtoupper(substr($ownerUser[0]['name'], 0, 1)) ?></div>
    <div>
        <p class="text-sm font-medium text-blue-900"><?= e($ownerUser[0]['name']) ?> <span class="text-xs bg-blue-200 text-blue-800 px-1.5 py-0.5 rounded">Owner</span></p>
        <p class="text-xs text-blue-700"><?= e($ownerUser[0]['email']) ?></p>
    </div>
</div>
<?php endif; ?>

<!-- Staff List -->
<?php if (!empty($staffList)): ?>
<div class="space-y-2 mb-6">
    <?php foreach ($staffList as $staff): ?>
    <div class="flex items-center justify-between p-3 bg-slate-50 rounded-lg border border-slate-200">
        <div class="flex items-center gap-3">
            <div class="w-8 h-8 bg-slate-300 rounded-full flex items-center justify-center text-slate-700 text-sm font-bold"><?= strtoupper(substr($staff['name'], 0, 1)) ?></div>
            <div>
                <p class="text-sm font-medium text-slate-800"><?= e($staff['name']) ?></p>
                <p class="text-xs text-slate-500"><?= e($staff['email']) ?> · <span class="<?= $staff['status'] === 'active' ? 'text-emerald-600' : 'text-red-600' ?>"><?= ucfirst($staff['status']) ?></span></p>
                <?php if (!empty($staff['permissions'])): ?>
                <div class="flex gap-1 mt-1"><?php foreach ((array)$staff['permissions'] as $perm): ?><span class="text-xs bg-slate-200 text-slate-600 px-1.5 py-0.5 rounded"><?= e($perm) ?></span><?php endforeach; ?></div>
                <?php endif; ?>
            </div>
        </div>
        <form method="POST" onsubmit="return confirm('Hapus staff ini?')">
            <?= csrf_field() ?><input type="hidden" name="_action" value="remove_staff"><input type="hidden" name="_tab" value="staff"><input type="hidden" name="staff_id" value="<?= $staff['id'] ?>">
            <button class="text-red-500 hover:text-red-700 text-xs font-medium">Hapus</button>
        </form>
    </div>
    <?php endforeach; ?>
</div>
<?php else: ?>
<p class="text-sm text-slate-400 mb-4">Belum ada staff.</p>
<?php endif; ?>

<!-- Add Staff Form -->
<div class="border-t border-slate-200 pt-4">
    <h4 class="text-sm font-semibold text-slate-700 mb-3">Tambah Staff Baru</h4>
    <form method="POST" class="space-y-3">
        <?= csrf_field() ?>
        <input type="hidden" name="_action" value="add_staff">
        <input type="hidden" name="_tab" value="staff">
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <input type="text" name="staff_name" required placeholder="Nama Staff" class="px-4 py-2.5 border border-slate-300 rounded-lg text-sm">
            <input type="email" name="staff_email" required placeholder="Email" class="px-4 py-2.5 border border-slate-300 rounded-lg text-sm">
        </div>
        <input type="password" name="staff_password" required minlength="8" placeholder="Password (min 8)" class="w-full px-4 py-2.5 border border-slate-300 rounded-lg text-sm">
        <div>
            <p class="text-xs text-slate-500 mb-2">Permissions:</p>
            <div class="flex flex-wrap gap-2">
                <?php foreach (['view_transactions','create_payment','view_wallet','view_withdrawals','manage_webhook'] as $perm): ?>
                <label class="flex items-center gap-1.5 text-xs bg-slate-100 px-2.5 py-1.5 rounded cursor-pointer hover:bg-slate-200">
                    <input type="checkbox" name="permissions[]" value="<?= $perm ?>" class="w-3.5 h-3.5 rounded">
                    <?= ucfirst(str_replace('_', ' ', $perm)) ?>
                </label>
                <?php endforeach; ?>
            </div>
        </div>
        <button type="submit" class="px-4 py-2.5 bg-emerald-600 text-white rounded-lg text-sm font-medium hover:bg-emerald-700">Tambah Staff</button>
    </form>
</div>


<?php elseif ($activeTab === 'wallet'): ?>
<h3 class="text-lg font-semibold text-slate-800 mb-4">Wallet Merchant</h3>
<div class="grid grid-cols-2 sm:grid-cols-3 gap-4 mb-6">
    <div class="p-4 bg-emerald-50 border border-emerald-200 rounded-lg">
        <p class="text-xs text-emerald-600">Available</p>
        <p class="text-lg font-bold text-emerald-700"><?= format_currency($wallet['available_balance'] ?? 0) ?></p>
    </div>
    <div class="p-4 bg-amber-50 border border-amber-200 rounded-lg">
        <p class="text-xs text-amber-600">Hold</p>
        <p class="text-lg font-bold text-amber-700"><?= format_currency($wallet['hold_balance'] ?? 0) ?></p>
    </div>
    <div class="p-4 bg-slate-50 border border-slate-200 rounded-lg">
        <p class="text-xs text-slate-500">Withdrawn</p>
        <p class="text-lg font-bold text-slate-700"><?= format_currency($wallet['withdrawn_balance'] ?? 0) ?></p>
    </div>
    <div class="p-4 bg-blue-50 border border-blue-200 rounded-lg">
        <p class="text-xs text-blue-600">Total Received</p>
        <p class="text-lg font-bold text-blue-700"><?= format_currency($wallet['total_received'] ?? 0) ?></p>
    </div>
    <div class="p-4 bg-red-50 border border-red-200 rounded-lg">
        <p class="text-xs text-red-600">Total Fee</p>
        <p class="text-lg font-bold text-red-700"><?= format_currency($wallet['total_fee'] ?? 0) ?></p>
    </div>
    <div class="p-4 bg-slate-50 border border-slate-200 rounded-lg">
        <p class="text-xs text-slate-500">Pending Balance</p>
        <p class="text-lg font-bold text-slate-700"><?= format_currency($wallet['pending_balance'] ?? 0) ?></p>
    </div>
</div>
<p class="text-xs text-slate-400">Wallet ID: <?= e($wallet['id'] ?? 'N/A') ?> | Updated: <?= format_date($wallet['updated_at'] ?? '') ?></p>
<?php endif; ?>

</div>
</div>

<?php require_once __DIR__ . '/../includes/admin_footer.php'; ?>
